### ISSUE TITLE
Having trouble installing.... 

### ISSUE THREAD

**Issue by sticilface** [andrei-tatar/node-red-contrib-ui#47]
```
root@test:/ # npm install node-red-contrib-ui





> node-icu-charset-detector@0.0.7 install /node_modules/node-icu-charset-detector


> node-gyp rebuild





gmake: Entering directory '/node_modules/node-icu-charset-detector/build'


  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o


cc1plus: error: unrecognized command line option "-std=gnu++0x"


node-icu-charset-detector.target.mk:84: recipe for target 'Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o' failed


gmake: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1


gmake: Leaving directory '/node_modules/node-icu-charset-detector/build'


gyp ERR! build error 


gyp ERR! stack Error: `gmake` failed with exit code: 2


gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)


gyp ERR! stack     at emitTwo (events.js:106:13)


gyp ERR! stack     at ChildProcess.emit (events.js:191:7)


gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)


gyp ERR! System FreeBSD 9.2-RELEASE-p15


gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"


gyp ERR! cwd /node_modules/node-icu-charset-detector


gyp ERR! node -v v6.1.0


gyp ERR! node-gyp -v v3.3.1


gyp ERR! not ok 


npm WARN install:node-icu-charset-detector@0.0.7 node-icu-charset-detector@0.0.7 install: `node-gyp rebuild`


npm WARN install:node-icu-charset-detector@0.0.7 Exit status 1


/


`-- node-red-contrib-ui@1.2.19 





npm WARN enoent ENOENT: no such file or directory, open '/package.json'


npm WARN !invalid#1 No description


npm WARN !invalid#1 No repository field.


npm WARN !invalid#1 No README data


npm WARN !invalid#1 No license field.
```

**Comment by sticilface** [comment]
Its on Freebsd.  FreeBSD 9.2-RELEASE-p15
